### ISSUE TITLE
Get Token request returned http error: 400

### ISSUE THREAD

**Issue by ajhewett** [wbuchwalter/Kubernetes-acs-engine-autoscaler#29]
kubernetes-acs-engine-autoscaler fails with the following error:

```
Traceback (most recent call last):
  File "/app/autoscaler/azure_api.py", line 20, in login
    tenant)
  File "/usr/local/lib/python3.6/site-packages/azure/cli/core/_profile.py", line 132, in find_subscriptions_on_login
    username, sp_auth, tenant, self._ad_resource_uri)
  File "/usr/local/lib/python3.6/site-packages/azure/cli/core/_profile.py", line 435, in find_from_service_principal_id
    token_entry = sp_auth.acquire_token(context, resource, client_id)
  File "/usr/local/lib/python3.6/site-packages/azure/cli/core/_profile.py", line 639, in acquire_token
    return authentication_context.acquire_token_with_client_credentials(resource, client_id, self.secret)
  File "/usr/local/lib/python3.6/site-packages/adal/authentication_context.py", line 160, in acquire_token_with_client_credentials
    return self._acquire_token(token_func)
  File "/usr/local/lib/python3.6/site-packages/adal/authentication_context.py", line 109, in _acquire_token
    return token_func(self)
  File "/usr/local/lib/python3.6/site-packages/adal/authentication_context.py", line 158, in token_func
    return token_request.get_token_with_client_credentials(client_secret)
  File "/usr/local/lib/python3.6/site-packages/adal/token_request.py", line 316, in get_token_with_client_credentials
    token = self._oauth_get_token(oauth_parameters)
  File "/usr/local/lib/python3.6/site-packages/adal/token_request.py", line 113, in _oauth_get_token
    return client.get_token(oauth_parameters)
  File "/usr/local/lib/python3.6/site-packages/adal/oauth2_client.py", line 281, in get_token
    raise AdalError(return_error_string, error_response)
adal.adal_error.AdalError: Get Token request returned http error: 400 and server response: <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN""http://www.w3.org/TR/html4/strict.dtd">
 <HTML><HEAD><TITLE>Bad Request</TITLE>
 <META HTTP-EQUIV="Content-Type" Content="text/html; charset=us-ascii"></HEAD>
 <BODY><h2>Bad Request - Invalid URL</h2>
 <hr><p>HTTP Error 400. The request URL is invalid.</p>
 </BODY></HTML>
 During handling of the above exception, another exception occurred:
 Traceback (most recent call last):
  File "main.py", line 111, in <module>
    main()
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "main.py", line 97, in main
    cluster.login()
  File "/app/autoscaler/cluster.py", line 66, in login
    self.service_principal_tenant_id)
  File "/app/autoscaler/azure_api.py", line 29, in login
    raise CLIError(err)
azure.cli.core.util.CLIError: Get Token request returned http error: 400 and server response: <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN""http://www.w3.org/TR/html4/strict.dtd">
 <HTML><HEAD><TITLE>Bad Request</TITLE>
 <META HTTP-EQUIV="Content-Type" Content="text/html; charset=us-ascii"></HEAD>
 <BODY><h2>Bad Request - Invalid URL</h2>
 <hr><p>HTTP Error 400. The request URL is invalid.</p>
 </BODY></HTML>
```

I am using an acs-generated Kubernetes 1.6.6 cluster with a secret containing base64 encoded values from `az ad sp create-for-rbac` and private keys from `azuredeploy.parameters.json`. The same error occurs with both the 0.3.0 and 1.0.0 `wbuchwalter/kubernetes-acs-engine-autoscaler` docker images.

**Comment by wbuchwalter** [comment]
Which region is your cluster hosted in? Are you on the Azure German Cloud by any chance? (https://github.com/Azure/azure-xplat-cli/issues/3391)

**Comment by ajhewett** [comment]
Problem solved.

I had used something like `echo "C89EB391-784B-46A2-A0C6-F81515300437" | base64` to encode `azure-sp-app-id`, `azure-sp-secret` and `azure-sp-tenant-id`.  This adds a newline character.

Instead, using `echo -n "C89EB391-784B-46A2-A0C6-F81515300437" | base64` omits the newline character and correctly encodes the secret.

It might be worthwhile to add a hint in the instructions about correctly base64-encoding the secrets.

BTW: The cluster is hosted in westeurope.
