### ISSUE TITLE
Auth 404

### ISSUE THREAD

**Issue by jskulavik** [wbuchwalter/Kubernetes-acs-engine-autoscaler#33]
Thanks for the fantastic tool folks.

When following the instructions and checking the logs of the pod created by using the example autoscale deployment I receive the following 404 auth error:

Traceback (most recent call last):
  File "/app/autoscaler/azure_api.py", line 20, in login
    tenant)
  File "/usr/local/lib/python3.6/site-packages/azure/cli/core/_profile.py", line 137, in find_subscriptions_on_login
    username, sp_auth, tenant, self._ad_resource_uri)
  File "/usr/local/lib/python3.6/site-packages/azure/cli/core/_profile.py", line 425, in find_from_service_principal_id
    token_entry = sp_auth.acquire_token(context, resource, client_id)
  File "/usr/local/lib/python3.6/site-packages/azure/cli/core/_profile.py", line 632, in acquire_token
    self.secret)
  File "/usr/local/lib/python3.6/site-packages/adal/authentication_context.py", line 160, in acquire_token_with_client_credentials
    return self._acquire_token(token_func)
  File "/usr/local/lib/python3.6/site-packages/adal/authentication_context.py", line 109, in _acquire_token
    return token_func(self)
  File "/usr/local/lib/python3.6/site-packages/adal/authentication_context.py", line 158, in token_func
    return token_request.get_token_with_client_credentials(client_secret)
  File "/usr/local/lib/python3.6/site-packages/adal/token_request.py", line 316, in get_token_with_client_credentials
    token = self._oauth_get_token(oauth_parameters)
  File "/usr/local/lib/python3.6/site-packages/adal/token_request.py", line 113, in _oauth_get_token
    return client.get_token(oauth_parameters)
  File "/usr/local/lib/python3.6/site-packages/adal/oauth2_client.py", line 281, in get_token
    raise AdalError(return_error_string, error_response)
adal.adal_error.AdalError: Get Token request returned http error: 400 and server response: <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN""http://www.w3.org/TR/html4/strict.dtd">
<HTML><HEAD><TITLE>Bad Request</TITLE>
<META HTTP-EQUIV="Content-Type" Content="text/html; charset=us-ascii"></HEAD>
<BODY><h2>Bad Request - Invalid URL</h2>
<hr><p>HTTP Error 400. The request URL is invalid.</p>
</BODY></HTML>

**Comment by wbuchwalter** [comment]
Hey @jskulavik, 
could it be the same issue as #29?

**Comment by jskulavik** [comment]
Ahh, perhaps.  I used the `-w 0` option.  I'll try `-n` instead.  Thank you @wbuchwalter!

**Comment by wbuchwalter** [comment]
Closing then, but feel free to reopen if that doesn't fix.
