### ISSUE TITLE
Issue when deploying autoscaler

### ISSUE THREAD

**Issue by hmarcelodn** [wbuchwalter/Kubernetes-acs-engine-autoscaler#51]
I ran the instructions and the pods are not running. I am seeing the following error:
```bash

Traceback (most recent call last):
  File "main.py", line 113, in <module>
    main()
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "main.py", line 99, in main
    cluster.login()
  File "/app/autoscaler/cluster.py", line 71, in login
    self.arm_template = download_template(self.resource_group, self.acs_deployment)
  File "/app/autoscaler/azure_api.py", line 40, in download_template
    return resource_management_client.deployments.export_template(resource_group_name, acs_deployment).template
  File "/usr/local/lib/python3.6/site-packages/azure/mgmt/resource/resources/v2017_05_10/operations/deployments_operations.py", line 537, in export_template
    raise exp
msrestazure.azure_exceptions.CloudError: Azure Error: DeploymentNotFound
Message: Deployment 'azuredeploy' could not be found. 
```

Any ideas?

**Comment by hmarcelodn** [comment]
#37 Closed by related

**Comment by MirzaSikander** [comment]
How were you able to figure this out? I am running into the same issue.

Followed the instructions and populated the values.yaml file, and used helm to deploy it on to the cluster.

**Comment by MirzaSikander** [comment]
Okay so figured it out. Acs-engine now creates the deployment with the `<resource group name>-<random number>` so the default `azuredeploy` does not work anymore. It can be found on azure portal.

In the values.yaml file specify the parameter.
```
acsenginecluster:
  acsdeployment: <deployment name>
```
