### ISSUE TITLE
Hybrid ACS Engine Cluster (*Nix & Windows)

### ISSUE THREAD

**Issue by lauxtermann-aram** [wbuchwalter/Kubernetes-acs-engine-autoscaler#53]
Hi, 

I keep getting this error:
```
Traceback (most recent call last):
  File "main.py", line 113, in <module>
    main()
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "main.py", line 102, in main
    scaled = cluster.loop(debug)
  File "/app/autoscaler/cluster.py", line 110, in loop
    return self.loop_logic()
  File "/app/autoscaler/cluster.py", line 132, in loop_logic
    all_nodes = list(filter(utils.is_agent, map(self.create_kube_node, pykube_nodes)))
  File "/app/autoscaler/cluster.py", line 121, in create_kube_node
    kube_node = KubeNode(node)
  File "/app/autoscaler/kube.py", line 98, in __init__
    self.index = int(self.name.split('-')[3])
IndexError: list index out of range
```

But my secrets are definitely correct. Does anyone know the answer?
TNX

**Comment by wbuchwalter** [comment]
Hi,
This issue is addressed in the README (a bit hidden at the very bottom):
> Currently node pools with Windows machines are not supported. If a Windows pool is part of the deployment the autoscaler will fail even for scaling Linux-based node pools.

**Comment by lauxtermann-aram** [comment]
My apologies! Tnx for the quick response! I'll close this one!
